var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/firewall/agent-sync/route.js")
R.c("server/chunks/[root-of-the-server]__0btlx-r._.js")
R.c("server/chunks/node_modules_next_dist_0asuiw2._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/node_modules_1z0tebx._.js")
R.c("server/chunks/[root-of-the-server]__02_2sm-._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_next-internal_server_app_api_firewall_agent-sync_route_actions_1t48_zd.js")
R.m(52979)
module.exports=R.m(52979).exports
