var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/connections/[id]/favorite/route.js")
R.c("server/chunks/_0kiez00._.js")
R.c("server/chunks/[root-of-the-server]__1o4rf7u._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/node_modules_next_dist_0asuiw2._.js")
R.c("server/chunks/[root-of-the-server]__02_2sm-._.js")
R.c("server/chunks/[root-of-the-server]__1txqi6i._.js")
R.c("server/chunks/node_modules_1z0tebx._.js")
R.c("server/chunks/_next-internal_server_app_api_connections_[id]_favorite_route_actions_1ue45uo.js")
R.m(64683)
module.exports=R.m(64683).exports
