var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/mongo-sync/restore/route.js")
R.c("server/chunks/node_modules_next-auth_jwt_index_210rp25.js")
R.c("server/chunks/_0-hcwek._.js")
R.c("server/chunks/[root-of-the-server]__0sfn3x7._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/[root-of-the-server]__14et1fi._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0k82xso.js")
R.c("server/chunks/[root-of-the-server]__02_2sm-._.js")
R.c("server/chunks/[root-of-the-server]__1txqi6i._.js")
R.c("server/chunks/node_modules_1z0tebx._.js")
R.c("server/chunks/node_modules_next_dist_0asuiw2._.js")
R.c("server/chunks/src_15hb7aq._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_next-internal_server_app_api_mongo-sync_restore_route_actions_09npqbk.js")
R.m(98023)
module.exports=R.m(98023).exports
