var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/connections/[id]/query/route.js")
R.c("server/chunks/_1j423cc._.js")
R.c("server/chunks/[root-of-the-server]__0sfn3x7._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0k82xso.js")
R.c("server/chunks/_0kad--t._.js")
R.c("server/chunks/node_modules_1z0tebx._.js")
R.c("server/chunks/[root-of-the-server]__1txqi6i._.js")
R.c("server/chunks/[root-of-the-server]__02_2sm-._.js")
R.c("server/chunks/node_modules_next_dist_0asuiw2._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/[root-of-the-server]__01s3iue._.js")
R.c("server/chunks/_next-internal_server_app_api_connections_[id]_query_route_actions_0_6b7eo.js")
R.m(84064)
module.exports=R.m(84064).exports
