var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/webhooks/kofi/route.js")
R.c("server/chunks/src_06yrvtb._.js")
R.c("server/chunks/[root-of-the-server]__1eeg-su._.js")
R.c("server/chunks/_1k43yy0._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/[root-of-the-server]__02_2sm-._.js")
R.c("server/chunks/node_modules_1z0tebx._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/node_modules_next_dist_0asuiw2._.js")
R.c("server/chunks/_next-internal_server_app_api_webhooks_kofi_route_actions_08x6ixz.js")
R.m(54919)
module.exports=R.m(54919).exports
