var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/relay/token/route.js")
R.c("server/chunks/[root-of-the-server]__1lru8g7._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/[root-of-the-server]__1eeg-su._.js")
R.c("server/chunks/node_modules_next_dist_0asuiw2._.js")
R.c("server/chunks/node_modules_1z0tebx._.js")
R.c("server/chunks/[root-of-the-server]__02_2sm-._.js")
R.c("server/chunks/_1k1g691._.js")
R.c("server/chunks/_next-internal_server_app_api_relay_token_route_actions_20o7_qk.js")
R.m(68680)
module.exports=R.m(68680).exports
