module.exports=[2641,e=>e.a(async(s,t)=>{try{var n=e.i(64328),a=e.i(115),r=e.i(23862),o=e.i(64105),i=e.i(51631),l=s([r]);function u(e){return{...e,_id:e.id?.toString(),type:e.type||"ssh",dbProvider:e.dbprovider||e.dbProvider||"mongodb",authType:e.authtype||e.authType||"password",privateKey:e.privatekey||e.privateKey||null,keyFileName:e.keyfilename||e.keyFileName||null,passphrase:e.passphrase||null,tags:("string"==typeof e.tags?JSON.parse(e.tags):e.tags)||[],isFavorite:!!(void 0!==e.isfavorite?e.isfavorite:e.isFavorite),isSrv:!!(void 0!==e.issrv?e.issrv:e.isSrv),sshTunnel:!!(void 0!==e.sshtunnel?e.sshtunnel:e.sshTunnel),sshTunnelHost:e.sshtunnelhost||e.sshTunnelHost||null,sshTunnelPort:e.sshtunnelport||e.sshTunnelPort||22,sshTunnelUser:e.sshtunneluser||e.sshTunnelUser||null,sshTunnelAuth:e.sshtunnelauth||e.sshTunnelAuth||"password",sshTunnelPassword:e.sshtunnelpassword||e.sshTunnelPassword||null,sshTunnelPrivateKey:e.sshtunnelprivatekey||e.sshTunnelPrivateKey||null,sshTunnelPassphrase:e.sshtunnelpassphrase||e.sshTunnelPassphrase||null,lastConnected:e.lastconnected||e.lastConnected||null,createdAt:e.createdat||e.createdAt,updatedAt:e.updatedat||e.updatedAt,database:e.database_name||null}}async function T(e){if(!e)return[];if(e.startsWith("mongodb")){let s;try{if(1===n.default.connection.readyState){let e=n.default.models.Connection||(0,o.getConnectionModel)(n.default);return(await e.find({}).lean()).map(e=>({...e,_id:e._id?.toString()}))}s=await n.default.createConnection(e,{serverSelectionTimeoutMS:5e3}).asPromise();let t=(0,o.getConnectionModel)(s);return(await t.find({}).lean()).map(e=>({...e,_id:e._id?.toString()}))}catch(e){return i.logger.error("Migration: MongoDB read error:",e.message),[]}finally{if(s)try{await s.close()}catch(e){}}}if(e.startsWith("mysql://")){let s;try{s=a.default.createPool(e);let[t]=await s.execute("SHOW TABLES LIKE 'connections'");if(0===t.length)return[];let[n]=await s.execute("SELECT * FROM connections");return n.map(e=>u(e))}catch(e){return i.logger.error("Migration: MySQL read error:",e.message),[]}finally{if(s)try{await s.end()}catch(e){}}}if(e.startsWith("postgres://")||e.startsWith("postgresql://")){let s;try{if(s=new r.Client({connectionString:e,connectionTimeoutMillis:5e3}),await s.connect(),!(await s.query("SELECT to_regclass('public.connections') AS t")).rows[0].t)return[];return(await s.query("SELECT * FROM connections")).rows.map(e=>u(e))}catch(e){i.logger.error("Migration: PostgreSQL read error:",e.message)}finally{if(s)try{await s.end()}catch(e){}}}return[]}function h(e){return{type:e.type||"ssh",dbProvider:e.dbProvider||"mongodb",name:e.name,host:e.host,port:e.port||22,username:e.username||"",authType:e.authType||"password",password:e.password||null,database:e.database||e.database_name||null,privateKey:e.privateKey||null,keyFileName:e.keyFileName||null,passphrase:e.passphrase||null,tags:e.tags||[],color:e.color||"#6366f1",status:"unknown",isFavorite:!!e.isFavorite,isSrv:!!e.isSrv,notes:e.notes||"",sshTunnel:!!e.sshTunnel,sshTunnelHost:e.sshTunnelHost||null,sshTunnelPort:e.sshTunnelPort||22,sshTunnelUser:e.sshTunnelUser||null,sshTunnelAuth:e.sshTunnelAuth||"password",sshTunnelPassword:e.sshTunnelPassword||null,sshTunnelPrivateKey:e.sshTunnelPrivateKey||null,sshTunnelPassphrase:e.sshTunnelPassphrase||null}}async function A(e,s){if(!e||0===s.length)return{imported:0,skipped:0};let t=0,l=0;if(e.startsWith("mongodb")){let a;try{a=await n.default.createConnection(e,{serverSelectionTimeoutMS:5e3}).asPromise();let r=(0,o.getConnectionModel)(a);for(let e of s){if(!e.name||!e.host||await r.findOne({name:e.name,host:e.host})){l++;continue}await r.create(h(e)),t++}}catch(e){i.logger.error("Migration: MongoDB write error:",e.message)}finally{if(a)try{await a.close()}catch(e){}}}else if(e.startsWith("mysql://")){let n;try{for(let r of(n=a.default.createPool(e),await n.execute(`
        CREATE TABLE IF NOT EXISTS connections (
          id INT AUTO_INCREMENT PRIMARY KEY,
          type VARCHAR(20) DEFAULT 'ssh',
          dbProvider VARCHAR(20) DEFAULT 'mongodb',
          name VARCHAR(255) NOT NULL,
          host VARCHAR(255) NOT NULL,
          port INT DEFAULT 22,
          username VARCHAR(255) DEFAULT '',
          authType VARCHAR(20) DEFAULT 'password',
          password TEXT,
          database_name VARCHAR(255),
          privateKey TEXT,
          keyFileName VARCHAR(255),
          passphrase TEXT,
          tags JSON,
          color VARCHAR(20) DEFAULT '#6366f1',
          lastConnected DATETIME,
          status VARCHAR(20) DEFAULT 'unknown',
          isFavorite BOOLEAN DEFAULT FALSE,
          isSrv BOOLEAN DEFAULT FALSE,
          sshTunnel BOOLEAN DEFAULT FALSE,
          sshTunnelHost VARCHAR(255),
          sshTunnelPort INT DEFAULT 22,
          sshTunnelUser VARCHAR(255),
          sshTunnelAuth VARCHAR(20) DEFAULT 'password',
          sshTunnelPassword TEXT,
          sshTunnelPrivateKey TEXT,
          sshTunnelPassphrase TEXT,
          notes TEXT,
          createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
          updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        )
      `),s)){if(!r.name||!r.host){l++;continue}let[e]=await n.execute("SELECT id FROM connections WHERE name = ? AND host = ? LIMIT 1",[r.name,r.host]);if(e.length>0){l++;continue}let s=h(r);await n.execute(`INSERT INTO connections (type, dbProvider, name, host, port, username, authType, password, database_name, privateKey, keyFileName, passphrase, tags, color, status, isFavorite, isSrv, notes, sshTunnel, sshTunnelHost, sshTunnelPort, sshTunnelUser, sshTunnelAuth, sshTunnelPassword, sshTunnelPrivateKey, sshTunnelPassphrase)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,[s.type,s.dbProvider,s.name,s.host,s.port,s.username,s.authType,s.password,s.database,s.privateKey,s.keyFileName,s.passphrase,JSON.stringify(s.tags),s.color,s.status,+!!s.isFavorite,+!!s.isSrv,s.notes,+!!s.sshTunnel,s.sshTunnelHost,s.sshTunnelPort,s.sshTunnelUser,s.sshTunnelAuth,s.sshTunnelPassword,s.sshTunnelPrivateKey,s.sshTunnelPassphrase]),t++}}catch(e){i.logger.error("Migration: MySQL write error:",e.message)}finally{if(n)try{await n.end()}catch(e){}}}else if(e.startsWith("postgres://")||e.startsWith("postgresql://")){let n;try{for(let a of(n=new r.Client({connectionString:e,connectionTimeoutMillis:5e3}),await n.connect(),await n.query(`
        CREATE TABLE IF NOT EXISTS connections (
          id SERIAL PRIMARY KEY,
          type VARCHAR(20) DEFAULT 'ssh',
          dbProvider VARCHAR(20) DEFAULT 'mongodb',
          name VARCHAR(255) NOT NULL,
          host VARCHAR(255) NOT NULL,
          port INT DEFAULT 22,
          username VARCHAR(255) DEFAULT '',
          authType VARCHAR(20) DEFAULT 'password',
          password TEXT,
          database_name VARCHAR(255),
          privateKey TEXT,
          keyFileName VARCHAR(255),
          passphrase TEXT,
          tags JSONB,
          color VARCHAR(20) DEFAULT '#6366f1',
          lastConnected TIMESTAMP,
          status VARCHAR(20) DEFAULT 'unknown',
          isFavorite BOOLEAN DEFAULT FALSE,
          isSrv BOOLEAN DEFAULT FALSE,
          sshTunnel BOOLEAN DEFAULT FALSE,
          sshTunnelHost VARCHAR(255),
          sshTunnelPort INT DEFAULT 22,
          sshTunnelUser VARCHAR(255),
          sshTunnelAuth VARCHAR(20) DEFAULT 'password',
          sshTunnelPassword TEXT,
          sshTunnelPrivateKey TEXT,
          sshTunnelPassphrase TEXT,
          notes TEXT,
          createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
      `),s)){if(!a.name||!a.host||(await n.query("SELECT id FROM connections WHERE name = $1 AND host = $2 LIMIT 1",[a.name,a.host])).rows.length>0){l++;continue}let e=h(a);await n.query(`INSERT INTO connections (type, dbProvider, name, host, port, username, authType, password, database_name, privateKey, keyFileName, passphrase, tags, color, status, isFavorite, isSrv, notes, sshTunnel, sshTunnelHost, sshTunnelPort, sshTunnelUser, sshTunnelAuth, sshTunnelPassword, sshTunnelPrivateKey, sshTunnelPassphrase)
           VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26)`,[e.type,e.dbProvider,e.name,e.host,e.port,e.username,e.authType,e.password,e.database,e.privateKey,e.keyFileName,e.passphrase,JSON.stringify(e.tags),e.color,e.status,e.isFavorite,e.isSrv,e.notes,e.sshTunnel,e.sshTunnelHost,e.sshTunnelPort,e.sshTunnelUser,e.sshTunnelAuth,e.sshTunnelPassword,e.sshTunnelPrivateKey,e.sshTunnelPassphrase]),t++}}catch(e){i.logger.error("Migration: PostgreSQL write error:",e.message)}finally{if(n)try{await n.end()}catch(e){}}}return{imported:t,skipped:l}}async function d(e,s){if(!e||!s||e===s)return{success:!0,migrated:0,skipped:0,total:0};i.logger.info(`🔄 Migration: reading from ${e.substring(0,30)}...`);let t=await T(e);if(i.logger.info(`📦 Migration: found ${t.length} connections in source`),0===t.length)return{success:!0,migrated:0,skipped:0,total:0};i.logger.info(`📥 Migration: writing to ${s.substring(0,30)}...`);let{imported:n,skipped:a}=await A(s,t);return i.logger.info(`✅ Migration complete: ${n} imported, ${a} skipped`),{success:!0,migrated:n,skipped:a,total:t.length}}[r]=l.then?(await l)():l,e.s(["migrateConnections",0,d]),t()}catch(e){t(e)}},!1)];

//# sourceMappingURL=src_app_api_settings_database_migrate_migrator_0dzxu9o.js.map