module.exports=[54981,e=>{"use strict";var s=e.i(64105);e.s(["ConnectionRepository",0,class{constructor(e,s=null){this.db=e,this.userId=s||null,this.isMysql="mysql"===e.type,this.isPostgres="postgres"===e.type,this.isSql=this.isMysql||this.isPostgres}_rowOwnerId(e){let s=e?.userid??e?.userId??null;return null==s?null:String(s)}_owns(e){return!this.userId||this._rowOwnerId(e)===String(this.userId)}async init(){if(this.isMysql){await this.db.query(`
        CREATE TABLE IF NOT EXISTS connections (
          id INT AUTO_INCREMENT PRIMARY KEY,
          type ENUM('ssh', 'database') DEFAULT 'ssh',
          dbProvider ENUM('mongodb', 'mysql', 'postgres', 'sqlite') DEFAULT 'mongodb',
          name VARCHAR(255) NOT NULL,
          host VARCHAR(255) NOT NULL,
          port INT DEFAULT 22,
          username VARCHAR(255) DEFAULT '',
          authType ENUM('password', 'privateKey', 'none') DEFAULT 'password',
          password TEXT,
          database_name VARCHAR(255),
          privateKey TEXT,
          keyFileName VARCHAR(255),
          passphrase TEXT,
          tags JSON,
          color VARCHAR(20) DEFAULT '#6366f1',
          lastConnected DATETIME,
          status ENUM('online', 'offline', 'testing', 'unknown') DEFAULT 'unknown',
          isFavorite BOOLEAN DEFAULT FALSE,
          isSrv BOOLEAN DEFAULT FALSE,
          notes TEXT,
          createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
          updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        )
      `);try{await this.db.query("ALTER TABLE connections ADD COLUMN isSrv BOOLEAN DEFAULT FALSE")}catch(e){}try{await this.db.query("ALTER TABLE connections ADD COLUMN userId VARCHAR(64)"),await this.db.query("CREATE INDEX idx_connections_userId ON connections (userId)")}catch(e){}try{await this.db.query("ALTER TABLE connections ADD COLUMN authSource VARCHAR(255)")}catch(e){}try{await this.db.query("ALTER TABLE connections ADD COLUMN relayName VARCHAR(255)")}catch(e){}for(let e of["sshTunnel BOOLEAN DEFAULT FALSE","sshTunnelHost VARCHAR(255)","sshTunnelPort INT DEFAULT 22","sshTunnelUser VARCHAR(255)","sshTunnelAuth ENUM('password','privateKey') DEFAULT 'password'","sshTunnelPassword TEXT","sshTunnelPrivateKey TEXT","sshTunnelPassphrase TEXT"])try{await this.db.query(`ALTER TABLE connections ADD COLUMN ${e}`)}catch(e){}}else if(this.isPostgres){await this.db.query(`
        CREATE TABLE IF NOT EXISTS connections (
          id SERIAL PRIMARY KEY,
          type VARCHAR(20) DEFAULT 'ssh',
          dbProvider VARCHAR(20) DEFAULT 'mongodb',
          name VARCHAR(255) NOT NULL,
          host VARCHAR(255) NOT NULL,
          port INT DEFAULT 22,
          username VARCHAR(255) DEFAULT '',
          authType VARCHAR(20) DEFAULT 'password',
          password TEXT,
          database_name VARCHAR(255),
          privateKey TEXT,
          keyFileName VARCHAR(255),
          passphrase TEXT,
          tags JSONB,
          color VARCHAR(20) DEFAULT '#6366f1',
          lastConnected TIMESTAMP,
          status VARCHAR(20) DEFAULT 'unknown',
          isFavorite BOOLEAN DEFAULT FALSE,
          isSrv BOOLEAN DEFAULT FALSE,
          sshTunnel BOOLEAN DEFAULT FALSE,
          sshTunnelHost VARCHAR(255),
          sshTunnelPort INT DEFAULT 22,
          sshTunnelUser VARCHAR(255),
          sshTunnelAuth VARCHAR(20) DEFAULT 'password',
          sshTunnelPassword TEXT,
          sshTunnelPrivateKey TEXT,
          sshTunnelPassphrase TEXT,
          notes TEXT,
          createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
      `);try{await this.db.query("ALTER TABLE connections ADD COLUMN authSource VARCHAR(255)")}catch(e){}try{await this.db.query("ALTER TABLE connections ADD COLUMN relayName VARCHAR(255)")}catch(e){}try{await this.db.query("ALTER TABLE connections ADD COLUMN userId VARCHAR(64)"),await this.db.query("CREATE INDEX idx_connections_userId ON connections (userId)")}catch(e){}}}_mapSqlRow(e){return{...e,_id:e.id.toString(),type:e.type||"ssh",dbProvider:e.dbprovider||e.dbProvider||"mongodb",authType:e.authtype||e.authType||"password",privateKey:e.privatekey||e.privateKey||null,keyFileName:e.keyfilename||e.keyFileName||null,passphrase:e.passphrase||null,tags:("string"==typeof e.tags?JSON.parse(e.tags):e.tags)||[],isFavorite:!!(void 0!==e.isfavorite?e.isfavorite:e.isFavorite),isSrv:!!(void 0!==e.issrv?e.issrv:e.isSrv),authSource:e.authsource||e.authSource||null,sshTunnel:!!(void 0!==e.sshtunnel?e.sshtunnel:e.sshTunnel),sshTunnelHost:e.sshtunnelhost||e.sshTunnelHost||null,sshTunnelPort:e.sshtunnelport||e.sshTunnelPort||22,sshTunnelUser:e.sshtunneluser||e.sshTunnelUser||null,sshTunnelAuth:e.sshtunnelauth||e.sshTunnelAuth||"password",sshTunnelPassword:e.sshtunnelpassword||e.sshTunnelPassword||null,sshTunnelPrivateKey:e.sshtunnelprivatekey||e.sshTunnelPrivateKey||null,sshTunnelPassphrase:e.sshtunnelpassphrase||e.sshTunnelPassphrase||null,relayName:e.relayname||e.relayName||null,lastConnected:e.lastconnected||e.lastConnected||null,createdAt:e.createdat||e.createdAt,updatedAt:e.updatedat||e.updatedAt,database:e.database_name||null}}async findAll(){if(this.isSql){let e=this.userId?" WHERE userId = ?":"",s=this.userId?[this.userId]:[],t=await this.db.query(`SELECT * FROM connections${e} ORDER BY updatedAt DESC`,s);return(this.isPostgres?t.rows:t[0]).filter(e=>this._owns(e)).map(e=>this._mapSqlRow(e))}{let e=(0,s.getConnectionModel)(this.db),t=this.userId?e.find({userId:this.userId}).sort({updatedAt:-1}):e.find({}).sort({updatedAt:-1});return await t}}async findById(e){let t=String(e??"").trim();if(!t)return null;if(this.isSql){if(this.isPostgres&&!/^\d+$/.test(t))return null;let e=this.isPostgres?"SELECT * FROM connections WHERE id = $1":"SELECT * FROM connections WHERE id = ?",s=await this.db.query(e,[t]),n=this.isPostgres?s.rows:s[0];return 0!==n.length&&this._owns(n[0])?this._mapSqlRow(n[0]):null}{let e=(0,s.getConnectionModel)(this.db);try{let s=this.userId?{_id:t,userId:this.userId}:{_id:t};return await e.findOne(s)}catch(e){if("CastError"===e.name)return null;throw e}}}async findOne(e){if(this.isSql){let s=Object.keys(e);if(0===s.length)return null;let t=s.map((e,s)=>`${"database"===e?"database_name":e} = ${this.isPostgres?"$"+(s+1):"?"}`).join(" AND "),n=`SELECT * FROM connections WHERE ${t}`,i=[...Object.values(e)];this.userId&&(n+=this.isPostgres?` AND userId = $${i.length+1}`:" AND userId = ?",i.push(this.userId)),n+=" LIMIT 1";let r=await this.db.query(n,i),a=this.isPostgres?r.rows:r[0];return 0!==a.length&&this._owns(a[0])?this._mapSqlRow(a[0]):null}{let t=this.userId?{...e,userId:this.userId}:e,n=(0,s.getConnectionModel)(this.db);return await n.findOne(t)}}async create(e){if(this.isSql){let s=["type","dbProvider","name","host","port","username","authType","password","database_name","privateKey","keyFileName","passphrase","tags","color","status","isFavorite","isSrv","notes","sshTunnel","sshTunnelHost","sshTunnelPort","sshTunnelUser","sshTunnelAuth","sshTunnelPassword","sshTunnelPrivateKey","sshTunnelPassphrase","relayName"],t=[e.type||"ssh",e.dbProvider||e.dbprovider||"mongodb",e.name,e.host,e.port||22,e.username||"",e.authType||e.authtype||"password",e.password||null,e.database||e.database_name||null,e.privateKey||null,e.keyFileName||null,e.passphrase||null,JSON.stringify(e.tags||[]),e.color||"#6366f1",e.status||"unknown",this.isPostgres?!!e.isFavorite:+!!e.isFavorite,this.isPostgres?!!e.isSrv:+!!e.isSrv,e.notes||"",this.isPostgres?!!e.sshTunnel:+!!e.sshTunnel,e.sshTunnelHost||null,e.sshTunnelPort||22,e.sshTunnelUser||null,e.sshTunnelAuth||"password",e.sshTunnelPassword||null,e.sshTunnelPrivateKey||null,e.sshTunnelPassphrase||null,e.relayName||null];this.userId&&(s.unshift("userId"),t.unshift(this.userId));let n=this.isPostgres?s.map((e,s)=>"$"+(s+1)).join(", "):s.map(()=>"?").join(", "),i=`INSERT INTO connections (${s.join(", ")}) VALUES (${n}) ${this.isPostgres?"RETURNING id":""}`,r=await this.db.query(i,t);return{_id:(this.isPostgres?r.rows[0].id:r[0].insertId).toString(),name:e.name}}{let t=(0,s.getConnectionModel)(this.db),n=this.userId?{...e,userId:this.userId}:e;return await t.create(n)}}async update(e,t){if(this.isSql){if(this.isPostgres&&!/^\d+$/.test(String(e)))return!0;let s=[],n=[],i={database:"database_name"},r=0;for(let[e,a]of Object.entries(t)){if("_id"===e||"id"===e||"storage"===e||"connection"===e)continue;let t=i[e]||e;s.push(`${t} = ${this.isPostgres?"$"+ ++r:"?"}`),"tags"===e?n.push(JSON.stringify(a)):["isFavorite","isSrv","isPinned","system","sshTunnel"].includes(e)?n.push(this.isPostgres?!!a:+!!a):n.push(a)}if(0===s.length)return!0;n.push(e);let a=`UPDATE connections SET ${s.join(", ")} WHERE id = ${this.isPostgres?"$"+ ++r:"?"}`;return this.userId&&(a+=this.isPostgres?` AND userId = $${++r}`:" AND userId = ?"),this.userId&&n.push(this.userId),await this.db.query(a,n),!0}{let n=(0,s.getConnectionModel)(this.db),i=this.userId?{_id:e,userId:this.userId}:{_id:e};return await n.findOneAndUpdate(i,t,{new:!0})}}async delete(e){if(this.isSql){let s=this.isPostgres?"DELETE FROM connections WHERE id = $1":"DELETE FROM connections WHERE id = ?",t=[e];return this.userId&&(s+=this.isPostgres?" AND userId = $2":" AND userId = ?",t.push(this.userId)),await this.db.query(s,t),!0}{let t=(0,s.getConnectionModel)(this.db);return this.userId?await t.findOneAndDelete({_id:e,userId:this.userId}):await t.findByIdAndDelete(e)}}}])},64105,e=>{"use strict";var s=e.i(64328);let t=new s.default.Schema({userId:{type:String,default:null,index:!0},type:{type:String,enum:["ssh","database"],default:"ssh"},dbProvider:{type:String,enum:["mongodb","mysql","postgres","sqlite"],default:"mongodb"},name:{type:String,required:!0,trim:!0},host:{type:String,required:!0,trim:!0},port:{type:Number,default:22},username:{type:String,default:"",trim:!0},authType:{type:String,enum:["password","privateKey","none"],default:"password"},password:{type:String,default:null},database:{type:String,default:null},privateKey:{type:String,default:null},keyFileName:{type:String,default:null},passphrase:{type:String,default:null},tags:[{type:String,trim:!0}],color:{type:String,default:"#6366f1"},lastConnected:{type:Date,default:null},status:{type:String,enum:["online","offline","testing","unknown"],default:"unknown"},isFavorite:{type:Boolean,default:!1},isSrv:{type:Boolean,default:!1},authSource:{type:String,default:null},dbOptions:{type:s.default.Schema.Types.Mixed,default:null},notes:{type:String,default:""},info:{type:String,default:null},systemInfo:{distro:{type:String,default:null},os:{type:String,default:null},cpu:{type:String,default:null},cores:{type:Number,default:null},ram:{type:String,default:null},ramBytes:{type:Number,default:null},uptime:{type:String,default:null},hostname:{type:String,default:null},kernel:{type:String,default:null},fetchedAt:{type:Date,default:null}},sshTunnel:{type:Boolean,default:!1},sshTunnelHost:{type:String,default:null},sshTunnelPort:{type:Number,default:22},sshTunnelUser:{type:String,default:null},sshTunnelAuth:{type:String,enum:["password","privateKey"],default:"password"},sshTunnelPassword:{type:String,default:null},sshTunnelPrivateKey:{type:String,default:null},sshTunnelPassphrase:{type:String,default:null},relayName:{type:String,default:null}},{timestamps:!0});s.default.models.Connection||s.default.model("Connection",t),e.s(["getConnectionModel",0,function(e){let n=e||s.default;return n.models.Connection||n.model("Connection",t)}])}];

//# sourceMappingURL=src_1frbwda._.js.map