var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/ssh/memory/route.js")
R.c("server/chunks/[root-of-the-server]__0sfn3x7._.js")
R.c("server/chunks/_0a_jypy._.js")
R.c("server/chunks/node_modules_1z0tebx._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0k82xso.js")
R.c("server/chunks/[root-of-the-server]__0v_o3yy._.js")
R.c("server/chunks/[root-of-the-server]__02_2sm-._.js")
R.c("server/chunks/[root-of-the-server]__1txqi6i._.js")
R.c("server/chunks/node_modules_next_dist_0asuiw2._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/_next-internal_server_app_api_ssh_memory_route_actions_01-9em6.js")
R.m(7333)
module.exports=R.m(7333).exports
