var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/ai-usage/migrate-daily-limit/route.js")
R.c("server/chunks/[root-of-the-server]__1eeg-su._.js")
R.c("server/chunks/[root-of-the-server]__1df7rz6._.js")
R.c("server/chunks/node_modules_1z0tebx._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0k82xso.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/[root-of-the-server]__1txqi6i._.js")
R.c("server/chunks/[root-of-the-server]__02_2sm-._.js")
R.c("server/chunks/node_modules_next_dist_0asuiw2._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/1oeh_server_app_api_admin_ai-usage_migrate-daily-limit_route_actions_1wrlh2q.js")
R.m(47515)
module.exports=R.m(47515).exports
