var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/settings/database/route.js")
R.c("server/chunks/src_app_api_settings_database_migrate_migrator_0dzxu9o.js")
R.c("server/chunks/[root-of-the-server]__1_-nw3v._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/_1cgp5wu._.js")
R.c("server/chunks/node_modules_1z0tebx._.js")
R.c("server/chunks/[root-of-the-server]__02_2sm-._.js")
R.c("server/chunks/[root-of-the-server]__1txqi6i._.js")
R.c("server/chunks/node_modules_next_dist_0asuiw2._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_next-internal_server_app_api_settings_database_route_actions_1yaimbl.js")
R.m(58743)
module.exports=R.m(58743).exports
