var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/agents/openclaw/route.js")
R.c("server/chunks/_1esz9fq._.js")
R.c("server/chunks/[root-of-the-server]__14et1fi._.js")
R.c("server/chunks/[root-of-the-server]__0sfn3x7._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0k82xso.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/node_modules_next_dist_0asuiw2._.js")
R.c("server/chunks/[root-of-the-server]__1txqi6i._.js")
R.c("server/chunks/_0hlkmxs._.js")
R.c("server/chunks/node_modules_1z0tebx._.js")
R.c("server/chunks/src_1ynl27t._.js")
R.c("server/chunks/[root-of-the-server]__02_2sm-._.js")
R.c("server/chunks/_next-internal_server_app_api_agents_openclaw_route_actions_020bji7.js")
R.m(47810)
module.exports=R.m(47810).exports
