var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/wiki/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__0iul9qg._.js")
R.c("server/chunks/node_modules_next_dist_0asuiw2._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/node_modules_1z0tebx._.js")
R.c("server/chunks/[root-of-the-server]__02_2sm-._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_next-internal_server_app_api_wiki_[id]_route_actions_20a5ke_.js")
R.m(20811)
module.exports=R.m(20811).exports
