var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/wiki/chat/route.js")
R.c("server/chunks/[root-of-the-server]__1r7bxf4._.js")
R.c("server/chunks/[root-of-the-server]__0sfn3x7._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0k82xso.js")
R.c("server/chunks/_1pbr8uh._.js")
R.c("server/chunks/node_modules_1z0tebx._.js")
R.c("server/chunks/[root-of-the-server]__02_2sm-._.js")
R.c("server/chunks/[root-of-the-server]__1txqi6i._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/node_modules_next_dist_0asuiw2._.js")
R.c("server/chunks/[root-of-the-server]__04pj7ax._.js")
R.c("server/chunks/_next-internal_server_app_api_wiki_chat_route_actions_19bh5r9.js")
R.m(55177)
module.exports=R.m(55177).exports
