var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/rclone/remote/route.js")
R.c("server/chunks/_1prnvfu._.js")
R.c("server/chunks/_1cvcupe._.js")
R.c("server/chunks/[root-of-the-server]__1pu4go3._.js")
R.c("server/chunks/src_0w_wmvw._.js")
R.c("server/chunks/node_modules_1z0tebx._.js")
R.c("server/chunks/node_modules_next_dist_0asuiw2._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/[root-of-the-server]__02_2sm-._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_next-internal_server_app_api_rclone_remote_route_actions_0bim37p.js")
R.m(63640)
module.exports=R.m(63640).exports
